HZ: 10

NUM_OF_PARTICLES: 2000
INIT_X: 7.0
INIT_Y: 0.0
INIT_YAW: 1.5708
INIT_X_COV: 0.4
INIT_Y_COV: 0.4
INIT_YAW_COV: 0.4
MAX_RANGE: 20
RANGE_STEP: 5
X_COV_TH: 0.10
Y_COV_TH: 0.10
YAW_COV_TH: 0.05
ALPHA_1: 0.3
ALPHA_2: 0.3
ALPHA_3: 0.1
ALPHA_4: 0.1
ALPHA_SLOW: 0.001
ALPHA_FAST: 0.1
HIT_COV: 1.0
LAMBDA_SHORT: 0.1
Z_HIT: 0.95
Z_SHORT: 0.1
Z_MAX: 0.05
Z_RAND: 0.05
DISTANCE_TH: 0.10
ANGLE_TH: 0.15
SELECTION_RATE: 0.5

DISTANCE_DEV_RATE: 0.01
DIRECTION_DEV: 0.001