HZ: 10

# Init Pose
INIT_X: 7.0
INIT_Y: 0.0
INIT_YAW: 1.5708

# Motio Noise Parameter
MOTION_NOISE_NN: 0.01
MOTION_NOISE_NO: 0.01
MOTION_NOISE_ON: 0.001
MOTION_NOISE_OO: 0.001

# Measurement Noise Parameter
DISTANCE_NOISE_RATE: 0.001
DIRECTION_NOISE: 0.001