HZ: 10

# Init Pose
INIT_X: 0.0
INIT_Y: 0.0
INIT_YAW: 0.0

# Motio Noise Parameter
MOTION_NOISE_NN: 0.0
MOTION_NOISE_NO: 0.0
MOTION_NOISE_ON: 0.0
MOTION_NOISE_OO: 0.0

# Measurement Noise Parameter
DISTANCE_NOISE_RATE: 0.0
DIRECTION_NOISE: 0.0